Repository schmiedeone/vacabot, pull requests merged in 2020-10, with the labels that each got.

#9 Separated Slack bot docs from README
  README.md
  docs/SLACK_BOT.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 Use default vacation balance const instead of hardcoded
  vacabot/models/user.js
Labels: Easy, enhancement, hacktoberfest, hacktoberfest-accepted

#17 Chore/lint commits
  .eslintrc
  .lintstagedrc
  package.json
  vacabot/actions.js
  vacabot/db.js
  vacabot/models/user.js
  vacabot/models/vacation.js
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 Add prettier standard guidelines
  .prettierignore
  .prettierrc
  .vscode/settings.json
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 nodemon Setup
  package.json
  yarn.lock
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
